config/routes.rb
RailsDigest::Application.routes.draw do

  root to: 'posts#index'

  resources :posts, except: [:destroy]
  resources :categories, only: [:show]
  

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :post_categories
	has_many :posts ,through: :post_categories


end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
	belongs_to :user
	
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
	has_many :comments
	has_many :post_categories
	has_many :categories ,through: :post_categories

	validates :title, presence: true, length: {minimum: 5}
	validates :url, presence: true
	validates :description, presence: true, uniqueness: true

end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base

	belongs_to :post
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def show
		@category = Category.find(params[:id])
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :set_post, only: [:show, :edit, :update]

	def index
		@posts = Post.all
	end

	def show; end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.creator = User.first

		if @post.save
			flash[:notice] = "You post was created."
			redirect_to posts_path
		else
			render :new
		end
	end


	def edit; end


	def update

		if @post.update(post_params)
			flash[:notice] = "This post was updates."
			redirect_to post_path(@post)
		else
			render :edit
		end
	end


	private

	def post_params
		params.require(:post).permit(:title, :url, :description)
	end

	def set_post
		@post = Post.find(params[:id])
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_category.html.erb
<span class='badge'>
	<%= link_to category.name, category_path(category) %>
</span>

app/views/categories/show.html.erb
<% all_posts = link_to('All Posts', posts_path) %>
<%= render 'shared/content_title', title: "#{all_posts} &raquo; #{@category.name}".html_safe %>


<% @category.posts.each do |post| %>
   <%= render 'posts/post', post: post %> 
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://student.coolsea.net">大魏老師的資訊課程</a> by Coolsea
	</small>	

	<nav>
		<ul>
            <li class="pull-right"><a href="#top">Back to top</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "大魏靈感集中盒", root_path, id: "logo" %>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to "Home", root_path %></li>
						<li><%= link_to "New Post", new_post_path %></li>
						<li>
							<div class='btn-group nav_item'>
								<%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %> Categories <span class='caret'></span>
								<% end %>
								<ul class='dropdown-menu'>
									<% Category.all.each do |category| %>
										<li>
											<%= link_to category.name, category_path(category) %>
										</li>
									<% end %>
								</ul>
							</div>
						</li>
					</ul>
				</nav>
			</div>	
		</div>
	</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>大魏教學靈感收集</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

</head>
<body>
	<%= render 'layouts/header' %>

	<div class="container">

	<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>

	<%= yield %>
	<%= render 'layouts/footer' %>
	
	</div>

</body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
	<div class='row'>
		<div class="alert alert-error span8">
			<h5>Please fix following errors: </h5>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>

<div class='row'>
	<div class='well span6'>
		<%= form_for @post do |f| %>
			<div class='control-group'>
				<%= f.label :title %>
				<%= f.text_field :title %>
			</div>
			<div class='control-group'>
				<%= f.label :url %>
				<%= f.text_field :url %>
			</div>
			<div class='control-group'>
				<%= f.label :description %>
				<%= f.text_area :description, rows: 5 %>
			</div>

			<%= f.submit(@post.new_record? ? '發表' : '更新', class: 'btn btn-primary') %>
		<% end %>
	</div>
</div>

app/views/posts/_post.html.erb
  <div class='row'>
    <div class='span8 well'>
      <%= render post.categories %>

      <h4><%= link_to post.title, post.url %></h4>
      <p><%= post.description %></p>
      <p>
        <span class='quiet'>posted by</span> <%= post.creator.username %>
        <small>at <%= post.created_at %></small>
      </p>
      <small>
        <span>
          <%= link_to("#{post.comments.size} comments", post_path(post)) %>
        </span>
      </small>
    </div>
  </div>  

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit This Post' %>

<%= render 'form' %>

app/views/posts/index.html.erb
  <%= render 'shared/content_title', title: 'All Post' %>


<% @posts.each do |post| %>
  <%= render 'post', post: post %>  
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create New Post' %>

<%= render 'form' %>

app/views/posts/show.html.erb
<p>
  <% @post.categories.each do |category| %>
    <span class='badge'><%= category.name %></span>
  <% end %>

<p class='pull-right'>
	[<%= link_to 'edit this post', edit_post_path(@post) %>]
</p>

</p>
	<%= render 'shared/content_title', title: @post.title %>
<p>
	<%= @post.description %>
</p>

app/views/shared/_content_title.html.erb
<p class='lead'>
  <%= title %>
  <hr/>
</p>